name: FORSAKEN.photography
favicon: null
layout_spectrum: 0.38682
typography_spectrum: 0.46912
title: Edgy protraits in interesting places
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d7d5d8'
    - '#adadaf'
    - '#3e3c3d'
    - '#666666'
  brandStrength: 0.875
  lightness: 0
  saturation: 0.6436530365608633
  rhythmicContrast: 0
purpose: []
