name: FORSAKEN.photography
favicon: null
layout_spectrum: 0.8647
typography_spectrum: 0.46912
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d7d5d8'
    - '#adadaf'
    - '#3e3c3d'
    - '#666666'
  brandStrength: 0.9630588700529188
  lightness: 0.007067924598231912
  saturation: 0.6436530365608633
  rhythmicContrast: 0.75
purpose: []
